#!/bin/sh

echo "Running PHP tests..."
php artisan test
if [ $? -ne 0 ]; then
    echo "Tests failed. Please fix the failing tests before pushing."
    exit 1
fi

echo "Running frontend tests..."
npm run test
if [ $? -ne 0 ]; then
    echo "Frontend tests failed. Please fix the failing tests before pushing."
    exit 1
fi

echo "Running frontend tests..."
npm run test
if [ $? -ne 0 ]; then
    echo "Frontend tests failed. Please fix the failing tests before pushing."
    exit 1
fi

exit 0